/* Copyright 2021 andresteare
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "quantum.h"


#define LAYOUT( \
    K00, K01, K02, K03, K04, K05, K06, K07, K08, K09, K0A, K0B, K0C, K0D, K0E, K0F, K0G, K0H, K0I, K0J, K0K, K0L, \
    K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, K1A, K1B, K1C, K1D, K1E, K1F, K1G, K1H, K1I, K1J, K1K, K1L, \
    K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, K2A, K2B, K2C, K2D, K2E, K2F, K2G, K2H, K2I, K2J, K2K, K2L, \
    K30, K31, K32, K33, K34, K35, K36, K37, K38, K39, K3A, K3B, K3C, K3D, K3E, K3F, K3G, K3H, K3I, K3J, K3K, K3L, \
    K40, K41, K42, K43, K44, K45, K46, K47, K48, K49, K4A, K4B, K4C, K4D, K4E, K4F, K4G, K4H, K4I, K4J, K4K, K4L, \
    K50, K51, K52, K53, K54, K55, K56, K57, K58, K59, K5A, K5B, K5C, K5D, K5E, K5F, K5G, K5H, K5I, K5J, K5K, K5L  \
) { \
    { K00,  K02,  K04,  K06,  K08,  K0A,  K0C,  K0E,  K0G,  K0I,  K0K  }, \
    { K01,  K03,  K05,  K07,  K09,  K0B,  K0D,  K0F,  K0H,  K0J,  K0L  }, \
    { K10,  K12,  K14,  K16,  K18,  K1A,  K1C,  K1E,  K1G,  K1I,  K1K  }, \
    { K11,  K13,  K15,  K17,  K19,  K1B,  K1D,  K1F,  K1H,  K1J,  K1L  }, \
    { K20,  K22,  K24,  K26,  K28,  K2A,  K2C,  K2E,  K2G,  K2I,  K2K  }, \
    { K21,  K23,  K25,  K27,  K29,  K2B,  K2D,  K2F,  K2H,  K2J,  K2L  }, \
    { K30,  K32,  K34,  K36,  K38,  K3A,  K3C,  K3E,  K3G,  K3I,  K3K  }, \
    { K31,  K33,  K35,  K37,  K39,  K3B,  K3D,  K3F,  K3H,  K3J,  K3L  }, \
    { K40,  K42,  K44,  K46,  K48,  K4A,  K4C,  K4E,  K4G,  K4I,  K4K  }, \
    { K41,  K43,  K45,  K47,  K49,  K4B,  K4D,  K4F,  K4H,  K4J,  K4L  }, \
    { K50,  K52,  K54,  K56,  K58,  K5A,  K5C,  K5E,  K5G,  K5I,  K5K  }, \
    { K51,  K53,  K55,  K57,  K59,  K5B,  K5D,  K5F,  K5H,  K5J,  K5L  } \
}



// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/
